import { hmac } from '@noble/hashes/hmac.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex, utf8ToBytes } from '@noble/hashes/utils.js';

/**
 * Provably fair random number generation.
 *
 * Every game round is bound to a seed pair and a nonce:
 *   - serverSeed: 64 hex chars generated by the server, kept secret while active.
 *     Its SHA-256 (serverSeedHash) is shown to the player before they play.
 *   - clientSeed: chosen (or accepted) by the player.
 *   - nonce: 0, 1, 2, ... incremented by one for every round played with the pair.
 *
 * The byte stream of a round is the concatenation of
 *   HMAC_SHA256(key = utf8(serverSeed), message = utf8(`${clientSeed}:${nonce}:${cursor}`))
 * for cursor = 0, 1, 2, ...  Each 32-byte block yields eight big-endian uint32 values.
 *
 * Integers in [0, n) are drawn with rejection sampling so that every value is
 * exactly equally likely (no modulo bias). Shuffles use Fisher-Yates driven by int().
 *
 * After the player rotates the seed pair the old serverSeed is revealed and anyone
 * can recompute every outcome with this same module (see ../verify.ts).
 */

export interface Rng {
  /** Next uniformly distributed integer in [0, 2^32). */
  nextUint32(): number;
  /** Uniform integer in [0, n). n must be an integer in [1, 2^32]. */
  int(n: number): number;
}

export interface SeedTriple {
  serverSeed: string;
  clientSeed: string;
  nonce: number;
}

const TWO_POW_32 = 0x1_0000_0000;

/** Draws uniformly in [0, n) from any uint32 source using rejection sampling. */
export function uniformInt(nextUint32: () => number, n: number): number {
  if (!Number.isInteger(n) || n < 1 || n > TWO_POW_32) {
    throw new RangeError(`int(n): n must be an integer in [1, 2^32], got ${n}`);
  }
  // Largest multiple of n that fits in 2^32; values at or above it are rejected.
  const limit = TWO_POW_32 - (TWO_POW_32 % n);
  for (;;) {
    const x = nextUint32();
    if (x < limit) return x % n;
  }
}

/** Builds an Rng from a raw uint32 source (useful for tests with scripted values). */
export function rngFromUint32Source(nextUint32: () => number): Rng {
  return {
    nextUint32,
    int: (n) => uniformInt(nextUint32, n),
  };
}

export function hmacBlock(
  serverSeed: string,
  clientSeed: string,
  nonce: number,
  cursor: number,
): Uint8Array {
  return hmac(sha256, utf8ToBytes(serverSeed), utf8ToBytes(`${clientSeed}:${nonce}:${cursor}`));
}

/** Deterministic RNG for one round, derived from the seed pair and nonce. */
export function createRoundRng({ serverSeed, clientSeed, nonce }: SeedTriple): Rng {
  if (!Number.isSafeInteger(nonce) || nonce < 0) {
    throw new RangeError(`nonce must be a non-negative safe integer, got ${nonce}`);
  }
  let cursor = 0;
  let block: Uint8Array = new Uint8Array(0);
  let offset = 0;

  const nextUint32 = (): number => {
    if (offset + 4 > block.length) {
      block = hmacBlock(serverSeed, clientSeed, nonce, cursor++);
      offset = 0;
    }
    const value =
      ((block[offset]! << 24) |
        (block[offset + 1]! << 16) |
        (block[offset + 2]! << 8) |
        block[offset + 3]!) >>>
      0;
    offset += 4;
    return value;
  };

  return rngFromUint32Source(nextUint32);
}

/** In-place Fisher-Yates shuffle (from the last index down). Returns the same array. */
export function shuffleInPlace<T>(rng: Rng, items: T[]): T[] {
  for (let i = items.length - 1; i > 0; i--) {
    const j = rng.int(i + 1);
    const tmp = items[i]!;
    items[i] = items[j]!;
    items[j] = tmp;
  }
  return items;
}

/** SHA-256 of the server seed, as lowercase hex. This is the public commitment. */
export function hashServerSeed(serverSeed: string): string {
  return bytesToHex(sha256(utf8ToBytes(serverSeed)));
}

export const SERVER_SEED_PATTERN = /^[0-9a-f]{64}$/;
/** Client seeds: 1-64 printable ASCII characters, no colon (it separates HMAC message fields). */
export const CLIENT_SEED_PATTERN = /^[\x21-\x39\x3b-\x7e]{1,64}$/;

/**
 * Small, fast, seedable PRNG (mulberry32). NOT cryptographically secure:
 * only for tests and simulations where reproducibility matters.
 */
export function createSeededTestRng(seed: number): Rng {
  let a = seed >>> 0;
  return rngFromUint32Source(() => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return (t ^ (t >>> 14)) >>> 0;
  });
}
